inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - "tmp/**/*"
    - "config/initializers/*"
    - "vendor/**/*"
    - 'db/**/*'
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 6.0

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'spec/**/*'
