version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/webapp
      - tmp-data:/webapp/tmp/sockets
      - public-data:/webapp/public
      - log-data:/var/log/nginx
      - bundle:/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql

  web:
    build:
      context: containers/nginx
    volumes:
      - tmp-data:/webapp/tmp/sockets
      - public-data:/webapp/public
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  db-data:
  tmp-data:
    driver: local
  public-data:
    driver: local
  log-data:
    driver: local
  bundle:
    driver: local
